Stencyl
endlessm/stencyl-flatpak pull request #1
Opened 2017-03-01 08:35 UTC by LiliC

This PR enables the funconality of running and exporting your games to HTML5. As well as exporting to chrome web store.
I followed [this example](http://www.stencyl.com/help/view/crash-course/) to create a game and then run and export it. 

For other non working options I created tickets and wrote the problems on why it currently doesn't work.
https://phabricator.endlessm.com/T15415

2017-03-01 12:25 UTC, krnowak requested changes

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.appdata.xml
> +  <project_license>DMCA</project_license>
I'd say just "proprietary". DMCA stands for Digital Millenium Copyright Act and it's not a license in itself.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "url": "http://archive.ubuntu.com/ubuntu/pool/main/libx/libxext/libxext_1.3.0.orig.tar.gz",
I would be wary of using ubuntu packages, they are unclear about using their packages with their trademarks. Of course, IANAL. Also, why not use the upstream libxext - https://www.x.org/archive//individual/lib/libXext-1.3.0.tar.bz2

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "url": "http://de.archive.ubuntu.com/ubuntu/pool/main/libg/libgc/libgc1c2_7.4.2-8_amd64.deb",
I would be wary of using ubuntu packages, they are unclear about using their packages with their trademarks. Of course, IANAL. Also, why not use the upstream libgc - https://github.com/ivmai/bdwgc?

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "dest-filename": "com.stencyl.Game.desktop"
`dest-filename` is not necessary - it is by default the last part of the `path` field.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "dest-filename": "com.stencyl.Game.appdata.xml"
Not necessary.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "dest-filename": "com.stencyl.Game.png"
Not necessary.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "dest-filename": "stencyl.sh"
Not necessary.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "dest-filename": "firefox"
Not necessary.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "dest-filename": "apply_extra"
Not necessary.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +            "name": "java&resources",
Why having those together? I'd make two or three modules - `java`, `lib32` and `resources`.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                    "path": "Makefile",
This Makefile is related to resources part, so I'd rename it to `resources-Makefile` to avoid confusion whether the Makefile is for building the flatpak (it isn't) or it is used by `flatpak-builder`.

2017-03-01 12:25 UTC, krnowak commented on com.stencyl.Game.json
> +                        "for i in jdk6-debs/*.deb ; do echo $i ; dpkg-deb -x $i debroot ; done",
Everything inside java debs will be put into the `debroot` directory, but I don't see `debroot` to be references anywhere else. I mean - shouldn't you copy/move those files somewhere too?

2017-03-01 12:25 UTC, krnowak commented on Makefile
> +	ln -s /usr/lib/libpcre.so.1 /app/lib/libpcre.so.3
Maybe add a comment that stencil is a closed source software, so we couldn't build it. Instead we got a binary package which was likely built on Ubuntu, where the pcre library is installed as `libpcre.so.3`, whereas the similar, API (and hopefully ABI-) compatible pcre in the flatpak runtime is `libpcre.so.1`.

2017-03-07 09:12 UTC, krnowak requested changes
Some more nitpicks.

2017-03-07 09:12 UTC, krnowak commented on com.stencyl.Game.json
> +    "runtime": "com.endlessm.Sdk",
Ha, curious. Sdk as a runtime, instead of Platform. I guess it's for building stuff?

Anyway, the long term aim is to move away from endless flatpak platform/sdk for non-endless apps, but using it is fine as a temporary solution. Please add a TODO to the `README.md` about porting the flatpak to f.d.o. or GNOME runtimes together with the list of dependencies you needed from endless sdk/platform that are absent in the f.d.o. and GNOME runtimes.

2017-03-07 09:12 UTC, krnowak commented on com.stencyl.Game.json
> +            "name": "java&resources",
So, Lili told me that the modules would need a Makefile anyway, so she merged them into one. Not sure if I like the explanation, but fair enough for now.

2017-03-07 09:12 UTC, krnowak commented on com.stencyl.Game.json
> +                        "for i in jdk6-debs/*.deb ; do echo $i ; dpkg-deb -x $i debroot ; done",
Hm, now that you use the endless runtime, you could get rid of all java debs. You can always readd them later again, when porting to other runtime - this thing is already in the git history, so maybe a simple revert will be enough to get the java modules back.

2017-03-07 09:12 UTC, krnowak commented on com.stencyl.Game.appdata.xml
> +  <summary>Create games without code.</summary>
Remove the dot at the end, please.

2017-03-07 09:12 UTC, krnowak commented on com.stencyl.Game.appdata.xml
> +    Stencyl is the easiest way to create games for mobile, web and desktop without code.
The lack of the indentation here makes my eyes bleed. ;)

2017-03-08 09:24 UTC, LiliC commented
@krnowak I updated the PR, can you have another look. Thanks.

I left my old commits, which were based on gnome runtime, in case we want to switch in the future.

2017-03-08 09:45 UTC, krnowak requested changes
Two nitpicks, feel free to merge after you fix them.

2017-03-08 09:45 UTC, krnowak commented on README.md
> +- Switch to a non endless runtime
Could you write what would need to be done for this to happen? What would need to be taken from the endless sdk/runtime that does not exist in f.d.o. or GNOME runtimes? Like add java, 32bit libraries and so on.

2017-03-08 09:45 UTC, krnowak commented on com.stencyl.Game.appdata.xml
> +	    Stencyl is the easiest way to create games for mobile, web and desktop without code.
Haha, from one extreme to the other, from no indentation to an overindentation. :P

Consider not using tabs here, then.

2017-03-08 10:08 UTC, merged